// destinations-data.js
window.DESTINATIONS = [
  // ===== EUROPE =====
  { city:"Barcelona", country:"Spain", lat:41.3851, lon:2.1734, iata:"BCN", region:"Europe", budget:"thrifty", whyNow:"Tapas & beaches", socials:{ig:"barcelona"}, wiki:"Barcelona"},
  { city:"Valencia", country:"Spain", lat:39.4699, lon:-0.3763, iata:"VLC", region:"Europe", budget:"cheap", whyNow:"City of Arts & paella", socials:{ig:"valencia"}, wiki:"Valencia"},
  { city:"Alicante", country:"Spain", lat:38.3452, lon:-0.4810, iata:"ALC", region:"Europe", budget:"cheap", whyNow:"Costa Blanca sun", socials:{ig:"alicante"}, wiki:"Alicante"},
  { city:"Málaga", country:"Spain", lat:36.7213, lon:-4.4214, iata:"AGP", region:"Europe", budget:"cheap", whyNow:"Museums + beach", socials:{ig:"malaga"}, wiki:"Málaga"},
  { city:"Seville", country:"Spain", lat:37.3891, lon:-5.9845, iata:"SVQ", region:"Europe", budget:"thrifty", whyNow:"Alcázar & tapas", socials:{ig:"sevilla"}, wiki:"Seville"},
  { city:"Madrid", country:"Spain", lat:40.4168, lon:-3.7038, iata:"MAD", region:"Europe", budget:"thrifty", whyNow:"Museums & food", socials:{ig:"madrid"}, wiki:"Madrid"},
  { city:"Lisbon", country:"Portugal", lat:38.7223, lon:-9.1393, iata:"LIS", region:"Europe", budget:"thrifty", whyNow:"Miradouros & trams", socials:{ig:"lisbon"}, wiki:"Lisbon"},
  { city:"Porto", country:"Portugal", lat:41.1579, lon:-8.6291, iata:"OPO", region:"Europe", budget:"cheap", whyNow:"Wine & azulejos", socials:{ig:"porto"}, wiki:"Porto"},
  { city:"Faro", country:"Portugal", lat:37.0194, lon:-7.9304, iata:"FAO", region:"Europe", budget:"cheap", whyNow:"Algarve beaches", socials:{ig:"algarve"}, wiki:"Faro"},
  { city:"Nice", country:"France", lat:43.7102, lon:7.2620, iata:"NCE", region:"Europe", budget:"boujie", whyNow:"Riviera views", socials:{ig:"nicefrance"}, wiki:"Nice"},
  { city:"Marseille", country:"France", lat:43.2965, lon:5.3698, iata:"MRS", region:"Europe", budget:"thrifty", whyNow:"Calanques coast", socials:{ig:"marseille"}, wiki:"Marseille"},
  { city:"Cagliari", country:"Italy", lat:39.2238, lon:9.1217, iata:"CAG", region:"Europe", budget:"thrifty", whyNow:"Sardinia beaches", socials:{ig:"sardegna"}, wiki:"Cagliari"},
  { city:"Olbia", country:"Italy", lat:40.9234, lon:9.5037, iata:"OLB", region:"Europe", budget:"boujie", whyNow:"Costa Smeralda", socials:{ig:"costa_smeralda"}, wiki:"Olbia"},
  { city:"Palermo", country:"Italy", lat:38.1157, lon:13.3615, iata:"PMO", region:"Europe", budget:"thrifty", whyNow:"Sicilian food", socials:{ig:"palermo"}, wiki:"Palermo"},
  { city:"Catania", country:"Italy", lat:37.5079, lon:15.0830, iata:"CTA", region:"Europe", budget:"thrifty", whyNow:"Etna & coast", socials:{ig:"catania"}, wiki:"Catania"},
  { city:"Rome", country:"Italy", lat:41.9028, lon:12.4964, iata:"FCO", region:"Europe", budget:"boujie", whyNow:"Icons + gelato", socials:{ig:"rome"}, wiki:"Rome"},
  { city:"Naples", country:"Italy", lat:40.8518, lon:14.2681, iata:"NAP", region:"Europe", budget:"cheap", whyNow:"Pizza & Amalfi access", socials:{ig:"napoli"}, wiki:"Naples"},
  { city:"Athens", country:"Greece", lat:37.9838, lon:23.7275, iata:"ATH", region:"Europe", budget:"thrifty", whyNow:"Acropolis sunsets", socials:{ig:"athensgreece"}, wiki:"Athens"},
  { city:"Thessaloniki", country:"Greece", lat:40.6401, lon:22.9444, iata:"SKG", region:"Europe", budget:"cheap", whyNow:"Foodie port", socials:{ig:"thessaloniki"}, wiki:"Thessaloniki"},
  { city:"Heraklion (Crete)", country:"Greece", lat:35.3387, lon:25.1442, iata:"HER", region:"Europe", budget:"thrifty", whyNow:"Crete beaches", socials:{ig:"crete"}, wiki:"Heraklion"},
  { city:"Chania (Crete)", country:"Greece", lat:35.5138, lon:24.0180, iata:"CHQ", region:"Europe", budget:"thrifty", whyNow:"Balos & Elafonissi", socials:{ig:"chania"}, wiki:"Chania"},
  { city:"Rhodes", country:"Greece", lat:36.4340, lon:28.2176, iata:"RHO", region:"Europe", budget:"thrifty", whyNow:"Medieval + beach", socials:{ig:"rhodes"}, wiki:"Rhodes"},
  { city:"Larnaca", country:"Cyprus", lat:34.9003, lon:33.6232, iata:"LCA", region:"Europe", budget:"thrifty", whyNow:"Blue waters", socials:{ig:"cyprus"}, wiki:"Larnaca"},
  { city:"Paphos", country:"Cyprus", lat:34.7720, lon:32.4297, iata:"PFO", region:"Europe", budget:"thrifty", whyNow:"Resorts & ruins", socials:{ig:"paphos"}, wiki:"Paphos"},
  { city:"Dubrovnik", country:"Croatia", lat:42.6507, lon:18.0944, iata:"DBV", region:"Europe", budget:"boujie", whyNow:"Old Town on the sea", socials:{ig:"dubrovnik"}, wiki:"Dubrovnik"},
  { city:"Split", country:"Croatia", lat:43.5081, lon:16.4402, iata:"SPU", region:"Europe", budget:"thrifty", whyNow:"Islands gateway", socials:{ig:"splitcroatia"}, wiki:"Split"},
  { city:"Budva", country:"Montenegro", lat:42.2864, lon:18.8400, iata:"TGD", region:"Europe", budget:"thrifty", whyNow:"Adriatic sun", socials:{ig:"montenegro"}, wiki:"Budva"},
  { city:"Madeira (Funchal)", country:"Portugal", lat:32.6669, lon:-16.9241, iata:"FNC", region:"Atlantic Islands", budget:"thrifty", whyNow:"Levadas & cliffs", socials:{ig:"madeira"}, wiki:"Funchal"},
  { city:"Tenerife South", country:"Spain", lat:28.0464, lon:-16.5725, iata:"TFS", region:"Atlantic Islands", budget:"thrifty", whyNow:"Teide + beaches", socials:{ig:"tenerife"}, wiki:"Tenerife"},
  { city:"Gran Canaria", country:"Spain", lat:28.1235, lon:-15.4363, iata:"LPA", region:"Atlantic Islands", budget:"thrifty", whyNow:"Dunes & sun", socials:{ig:"grancanaria"}, wiki:"Gran_Canaria"},
  { city:"Lanzarote", country:"Spain", lat:28.9617, lon:-13.5470, iata:"ACE", region:"Atlantic Islands", budget:"thrifty", whyNow:"Volcanic beaches", socials:{ig:"lanzarote"}, wiki:"Lanzarote"},
  { city:"Azores (Ponta Delgada)", country:"Portugal", lat:37.7412, lon:-25.6756, iata:"PDL", region:"Atlantic Islands", budget:"thrifty", whyNow:"Lakes & thermal", socials:{ig:"azores"}, wiki:"Ponta_Delgada"},

  // ===== NORTH AFRICA / MIDDLE EAST =====
  { city:"Marrakesh", country:"Morocco", lat:31.6295, lon:-7.9811, iata:"RAK", region:"North Africa", budget:"thrifty", whyNow:"Riads & souks", socials:{ig:"marrakech"}, wiki:"Marrakesh"},
  { city:"Agadir", country:"Morocco", lat:30.4278, lon:-9.5981, iata:"AGA", region:"North Africa", budget:"cheap", whyNow:"Atlantic beaches", socials:{ig:"agadir"}, wiki:"Agadir"},
  { city:"Essaouira", country:"Morocco", lat:31.5085, lon:-9.7595, iata:"ESU", region:"North Africa", budget:"cheap", whyNow:"Wind & medina", socials:{ig:"essaouira"}, wiki:"Essaouira"},
  { city:"Casablanca", country:"Morocco", lat:33.5731, lon:-7.5898, iata:"CMN", region:"North Africa", budget:"thrifty", whyNow:"Gateway city", socials:{ig:"casablanca"}, wiki:"Casablanca"},
  { city:"Tunis", country:"Tunisia", lat:36.8065, lon:10.1815, iata:"TUN", region:"North Africa", budget:"cheap", whyNow:"Medina & coast", socials:{ig:"tunis"}, wiki:"Tunis"},
  { city:"Hammamet", country:"Tunisia", lat:36.4073, lon:10.6220, iata:"NBE", region:"North Africa", budget:"cheap", whyNow:"Beach resorts", socials:{ig:"hammamet"}, wiki:"Hammamet"},
  { city:"Hurghada", country:"Egypt", lat:27.2579, lon:33.8116, iata:"HRG", region:"North Africa", budget:"cheap", whyNow:"Red Sea sun", socials:{ig:"hurghada"}, wiki:"Hurghada"},
  { city:"Sharm El Sheikh", country:"Egypt", lat:27.9158, lon:34.3299, iata:"SSH", region:"North Africa", budget:"cheap", whyNow:"Reefs & resorts", socials:{ig:"sharmelsheikh"}, wiki:"Sharm_El_Sheikh"},
  { city:"Dubai", country:"UAE", lat:25.2048, lon:55.2708, iata:"DXB", region:"Middle East", budget:"expensive", whyNow:"City & desert", socials:{ig:"visitdubai"}, wiki:"Dubai"},
  { city:"Abu Dhabi", country:"UAE", lat:24.4539, lon:54.3773, iata:"AUH", region:"Middle East", budget:"boujie", whyNow:"Museums & beach", socials:{ig:"abudhabi"}, wiki:"Abu_Dhabi"},
  { city:"Doha", country:"Qatar", lat:25.2854, lon:51.5310, iata:"DOH", region:"Middle East", budget:"boujie", whyNow:"Corniche & museums", socials:{ig:"visitqatar"}, wiki:"Doha"},
  { city:"Muscat", country:"Oman", lat:23.5880, lon:58.3829, iata:"MCT", region:"Middle East", budget:"boujie", whyNow:"Wadis & beaches", socials:{ig:"oman"}, wiki:"Muscat"},
  { city:"Eilat", country:"Israel", lat:29.5577, lon:34.9519, iata:"ETM", region:"Middle East", budget:"thrifty", whyNow:"Red Sea sun", socials:{ig:"eilat"}, wiki:"Eilat"},

  // ===== SUB-SAHARAN AFRICA / INDIAN OCEAN =====
  { city:"Cape Town", country:"South Africa", lat:-33.9249, lon:18.4241, iata:"CPT", region:"Sub-Saharan Africa", budget:"thrifty", whyNow:"Mountains & ocean", socials:{ig:"capetown"}, wiki:"Cape_Town"},
  { city:"Durban", country:"South Africa", lat:-29.8587, lon:31.0218, iata:"DUR", region:"Sub-Saharan Africa", budget:"cheap", whyNow:"Warm Indian Ocean", socials:{ig:"durban"}, wiki:"Durban"},
  { city:"Maputo", country:"Mozambique", lat:-25.9655, lon:32.5892, iata:"MPM", region:"Sub-Saharan Africa", budget:"thrifty", whyNow:"Seafood & coast", socials:{ig:"maputo"}, wiki:"Maputo"},
  { city:"Zanzibar", country:"Tanzania", lat:-6.1659, lon:39.2026, iata:"ZNZ", region:"Sub-Saharan Africa", budget:"thrifty", whyNow:"Spice island", socials:{ig:"zanzibar"}, wiki:"Zanzibar"},
  { city:"Mombasa", country:"Kenya", lat:-4.0435, lon:39.6682, iata:"MBA", region:"Sub-Saharan Africa", budget:"cheap", whyNow:"Kenyan coast", socials:{ig:"mombasa"}, wiki:"Mombasa"},
  { city:"Seychelles (Mahé)", country:"Seychelles", lat:-4.6796, lon:55.4920, iata:"SEZ", region:"Indian Ocean", budget:"expensive", whyNow:"Granite beaches", socials:{ig:"seychelles"}, wiki:"Seychelles"},
  { city:"Mauritius", country:"Mauritius", lat:-20.3484, lon:57.5522, iata:"MRU", region:"Indian Ocean", budget:"boujie", whyNow:"Lagoon life", socials:{ig:"mauritius"}, wiki:"Mauritius"},
  { city:"Reunion (Saint-Denis)", country:"France", lat:-20.8821, lon:55.4507, iata:"RUN", region:"Indian Ocean", budget:"thrifty", whyNow:"Volcano hikes", socials:{ig:"reunionisland"}, wiki:"Réunion"},

  // ===== NORTH AMERICA =====
  { city:"Miami", country:"USA", lat:25.7617, lon:-80.1918, iata:"MIA", region:"North America", budget:"expensive", whyNow:"Beaches & nightlife", socials:{ig:"miami"}, wiki:"Miami"},
  { city:"Orlando", country:"USA", lat:28.5383, lon:-81.3792, iata:"MCO", region:"North America", budget:"thrifty", whyNow:"Parks & pools", socials:{ig:"orlando"}, wiki:"Orlando"},
  { city:"Tampa", country:"USA", lat:27.9506, lon:-82.4572, iata:"TPA", region:"North America", budget:"thrifty", whyNow:"Gulf beaches", socials:{ig:"tampa"}, wiki:"Tampa"},
  { city:"San Diego", country:"USA", lat:32.7157, lon:-117.1611, iata:"SAN", region:"North America", budget:"expensive", whyNow:"SoCal sun", socials:{ig:"sandiego"}, wiki:"San_Diego"},
  { city:"Los Angeles", country:"USA", lat:34.0522, lon:-118.2437, iata:"LAX", region:"North America", budget:"expensive", whyNow:"City + beach", socials:{ig:"losangeles"}, wiki:"Los_Angeles"},
  { city:"Palm Springs", country:"USA", lat:33.8303, lon:-116.5453, iata:"PSP", region:"North America", budget:"boujie", whyNow:"Desert pools", socials:{ig:"palmsprings"}, wiki:"Palm_Springs,_California"},
  { city:"Las Vegas", country:"USA", lat:36.1699, lon:-115.1398, iata:"LAS", region:"North America", budget:"thrifty", whyNow:"Pools & shows", socials:{ig:"lasvegas"}, wiki:"Las_Vegas"},
  { city:"Phoenix", country:"USA", lat:33.4484, lon:-112.0740, iata:"PHX", region:"North America", budget:"cheap", whyNow:"Desert heat", socials:{ig:"phoenix"}, wiki:"Phoenix,_Arizona"},
  { city:"Honolulu", country:"USA (Hawaii)", lat:21.3099, lon:-157.8581, iata:"HNL", region:"Oceania", budget:"expensive", whyNow:"Iconic surf", socials:{ig:"honolulu"}, wiki:"Honolulu"},
  { city:"San Juan", country:"Puerto Rico", lat:18.4655, lon:-66.1057, iata:"SJU", region:"Caribbean", budget:"thrifty", whyNow:"Warm & easy", socials:{ig:"sanjuan"}, wiki:"San_Juan,_Puerto_Rico"},
  { city:"Cancún", country:"Mexico", lat:21.1619, lon:-86.8515, iata:"CUN", region:"Caribbean", budget:"thrifty", whyNow:"Turquoise water", socials:{ig:"cancun"}, wiki:"Cancún"},
  { city:"Cabo San Lucas", country:"Mexico", lat:22.8905, lon:-109.9167, iata:"SJD", region:"North America", budget:"boujie", whyNow:"Baja beaches", socials:{ig:"cabosanlucas"}, wiki:"Cabo_San_Lucas"},

  // ===== CENTRAL AMERICA & CARIBBEAN =====
  { city:"Punta Cana", country:"Dominican Republic", lat:18.5601, lon:-68.3725, iata:"PUJ", region:"Caribbean", budget:"thrifty", whyNow:"Resort beaches", socials:{ig:"puntacana"}, wiki:"Punta_Cana"},
  { city:"Montego Bay", country:"Jamaica", lat:18.4762, lon:-77.8939, iata:"MBJ", region:"Caribbean", budget:"thrifty", whyNow:"Reggae & reefs", socials:{ig:"jamaica"}, wiki:"Montego_Bay"},
  { city:"Nassau", country:"Bahamas", lat:25.0443, lon:-77.3504, iata:"NAS", region:"Caribbean", budget:"boujie", whyNow:"Cays & sands", socials:{ig:"bahamas"}, wiki:"Nassau"},
  { city:"Aruba (Oranjestad)", country:"Aruba", lat:12.5211, lon:-69.9683, iata:"AUA", region:"Caribbean", budget:"boujie", whyNow:"Dry & sunny", socials:{ig:"aruba"}, wiki:"Aruba"},
  { city:"Barbados (Bridgetown)", country:"Barbados", lat:13.0975, lon:-59.6167, iata:"BGI", region:"Caribbean", budget:"boujie", whyNow:"West Coast beaches", socials:{ig:"barbados"}, wiki:"Barbados"},
  { city:"St Lucia (Castries)", country:"Saint Lucia", lat:14.0101, lon:-60.9875, iata:"UVF", region:"Caribbean", budget:"boujie", whyNow:"Pitons views", socials:{ig:"stlucia"}, wiki:"Saint_Lucia"},
  { city:"Costa Rica (Liberia)", country:"Costa Rica", lat:10.6350, lon:-85.4377, iata:"LIR", region:"Central America", budget:"thrifty", whyNow:"Pacific coast", socials:{ig:"costarica"}, wiki:"Liberia,_Costa_Rica"},
  { city:"Costa Rica (San José)", country:"Costa Rica", lat:9.9281, lon:-84.0907, iata:"SJO", region:"Central America", budget:"thrifty", whyNow:"Cloud forests + trips", socials:{ig:"costarica"}, wiki:"San_José,_Costa_Rica"},

  // ===== SOUTH AMERICA =====
  { city:"Rio de Janeiro", country:"Brazil", lat:-22.9068, lon:-43.1729, iata:"GIG", region:"Latin America", budget:"thrifty", whyNow:"Copacabana", socials:{ig:"riodejaneiro"}, wiki:"Rio_de_Janeiro"},
  { city:"São Paulo", country:"Brazil", lat:-23.5505, lon:-46.6333, iata:"GRU", region:"Latin America", budget:"thrifty", whyNow:"Big-city breaks", socials:{ig:"saopaulo"}, wiki:"São_Paulo"},
  { city:"Florianópolis", country:"Brazil", lat:-27.5949, lon:-48.5482, iata:"FLN", region:"Latin America", budget:"thrifty", whyNow:"Island beaches", socials:{ig:"floripa"}, wiki:"Florianópolis"},
  { city:"Buenos Aires", country:"Argentina", lat:-34.6037, lon:-58.3816, iata:"EZE", region:"Latin America", budget:"thrifty", whyNow:"City vibes", socials:{ig:"buenosaires"}, wiki:"Buenos_Aires"},
  { city:"Punta del Este", country:"Uruguay", lat:-34.9623, lon:-54.9511, iata:"PDP", region:"Latin America", budget:"boujie", whyNow:"Chic beach town", socials:{ig:"puntadeleste"}, wiki:"Punta_del_Este"},
  { city:"Santiago", country:"Chile", lat:-33.4489, lon:-70.6693, iata:"SCL", region:"Latin America", budget:"thrifty", whyNow:"Sun + Andes", socials:{ig:"santiago"}, wiki:"Santiago"},
  { city:"Cartagena", country:"Colombia", lat:10.3910, lon:-75.4794, iata:"CTG", region:"Latin America", budget:"thrifty", whyNow:"Walled city + beach", socials:{ig:"cartagena"}, wiki:"Cartagena,_Colombia"},
  { city:"Lima", country:"Peru", lat:-12.0464, lon:-77.0428, iata:"LIM", region:"Latin America", budget:"thrifty", whyNow:"Food capital", socials:{ig:"lima"}, wiki:"Lima"},

  // ===== SOUTH ASIA =====
  { city:"Goa", country:"India", lat:15.2993, lon:74.1240, iata:"GOI", region:"South Asia", budget:"cheap", whyNow:"Beaches & shacks", socials:{ig:"goa"}, wiki:"Goa"},
  { city:"Kochi", country:"India", lat:9.9312, lon:76.2673, iata:"COK", region:"South Asia", budget:"cheap", whyNow:"Kerala backwaters", socials:{ig:"kochi"}, wiki:"Kochi"},
  { city:"Colombo", country:"Sri Lanka", lat:6.9271, lon:79.8612, iata:"CMB", region:"South Asia", budget:"thrifty", whyNow:"Tea & coast", socials:{ig:"srilanka"}, wiki:"Colombo"},
  { city:"Malé", country:"Maldives", lat:4.1755, lon:73.5093, iata:"MLE", region:"Indian Ocean", budget:"expensive", whyNow:"Overwater villas", socials:{ig:"maldives"}, wiki:"Malé"},

  // ===== SOUTHEAST ASIA =====
  { city:"Bangkok", country:"Thailand", lat:13.7563, lon:100.5018, iata:"BKK", region:"Southeast Asia", budget:"cheap", whyNow:"Street food", socials:{ig:"bangkok"}, wiki:"Bangkok"},
  { city:"Phuket", country:"Thailand", lat:7.8804, lon:98.3923, iata:"HKT", region:"Southeast Asia", budget:"thrifty", whyNow:"Islands & food", socials:{ig:"phuket"}, wiki:"Phuket"},
  { city:"Krabi", country:"Thailand", lat:8.0863, lon:98.9063, iata:"KBV", region:"Southeast Asia", budget:"thrifty", whyNow:"Limestone bays", socials:{ig:"krabi"}, wiki:"Krabi"},
  { city:"Koh Samui", country:"Thailand", lat:9.5120, lon:100.0136, iata:"USM", region:"Southeast Asia", budget:"boujie", whyNow:"Island resorts", socials:{ig:"kohsamui"}, wiki:"Ko_Samui"},
  { city:"Da Nang", country:"Vietnam", lat:16.0544, lon:108.2022, iata:"DAD", region:"Southeast Asia", budget:"cheap", whyNow:"Beach & pagodas", socials:{ig:"danang"}, wiki:"Da_Nang"},
  { city:"Nha Trang", country:"Vietnam", lat:12.2388, lon:109.1967, iata:"CXR", region:"Southeast Asia", budget:"cheap", whyNow:"Resort coast", socials:{ig:"nhatrang"}, wiki:"Nha_Trang"},
  { city:"Hoi An (via Da Nang)", country:"Vietnam", lat:15.8801, lon:108.3380, iata:"DAD", region:"Southeast Asia", budget:"cheap", whyNow:"Heritage town", socials:{ig:"hoian"}, wiki:"Hội_An"},
  { city:"Bali (Denpasar)", country:"Indonesia", lat:-8.65, lon:115.2167, iata:"DPS", region:"Southeast Asia", budget:"thrifty", whyNow:"Surf & rice terraces", socials:{ig:"bali"}, wiki:"Denpasar"},
  { city:"Lombok", country:"Indonesia", lat:-8.6500, lon:116.3249, iata:"LOP", region:"Southeast Asia", budget:"cheap", whyNow:"Quieter than Bali", socials:{ig:"lombok"}, wiki:"Lombok"},
  { city:"Labuan Bajo (Flores)", country:"Indonesia", lat:-8.4964, lon:119.8877, iata:"LBJ", region:"Southeast Asia", budget:"thrifty", whyNow:"Komodo islands", socials:{ig:"labuanbajo"}, wiki:"Labuan_Bajo"},
  { city:"Singapore", country:"Singapore", lat:1.3521, lon:103.8198, iata:"SIN", region:"Southeast Asia", budget:"expensive", whyNow:"Clean & green", socials:{ig:"visitsingapore"}, wiki:"Singapore"},
  { city:"Kuala Lumpur", country:"Malaysia", lat:3.1390, lon:101.6869, iata:"KUL", region:"Southeast Asia", budget:"cheap", whyNow:"Food & skylines", socials:{ig:"kualalumpur"}, wiki:"Kuala_Lumpur"},
  { city:"Langkawi", country:"Malaysia", lat:6.35, lon:99.8, iata:"LGK", region:"Southeast Asia", budget:"thrifty", whyNow:"Duty-free islands", socials:{ig:"langkawi"}, wiki:"Langkawi"},
  { city:"Penang (George Town)", country:"Malaysia", lat:5.4141, lon:100.3288, iata:"PEN", region:"Southeast Asia", budget:"cheap", whyNow:"Street food capital", socials:{ig:"penang"}, wiki:"George_Town,_Penang"},
  { city:"Siem Reap", country:"Cambodia", lat:13.3671, lon:103.8448, iata:"SAI", region:"Southeast Asia", budget:"cheap", whyNow:"Angkor + pools", socials:{ig:"siemreap"}, wiki:"Siem_Reap"},
  { city:"Phu Quoc", country:"Vietnam", lat:10.2899, lon:103.9840, iata:"PQC", region:"Southeast Asia", budget:"thrifty", whyNow:"Island beaches", socials:{ig:"phuquoc"}, wiki:"Phú_Quốc"},
  { city:"Boracay (Caticlan)", country:"Philippines", lat:11.9804, lon:121.9189, iata:"MPH", region:"Southeast Asia", budget:"thrifty", whyNow:"White Beach", socials:{ig:"boracay"}, wiki:"Boracay"},
  { city:"Cebu", country:"Philippines", lat:10.3157, lon:123.8854, iata:"CEB", region:"Southeast Asia", budget:"cheap", whyNow:"Reefs & canyons", socials:{ig:"cebu"}, wiki:"Cebu"},
  { city:"El Nido (Palawan)", country:"Philippines", lat:11.2027, lon:119.4124, iata:"ENI", region:"Southeast Asia", budget:"boujie", whyNow:"Lagoons & karst", socials:{ig:"elnidopalawan"}, wiki:"El_Nido,_Palawan"},

  // ===== EAST ASIA =====
  { city:"Okinawa (Naha)", country:"Japan", lat:26.2124, lon:127.6809, iata:"OKA", region:"East Asia", budget:"boujie", whyNow:"Subtropical beaches", socials:{ig:"okinawa"}, wiki:"Okinawa"},
  { city:"Ishigaki", country:"Japan", lat:24.3400, lon:124.1550, iata:"ISG", region:"East Asia", budget:"boujie", whyNow:"Yaeyama islands", socials:{ig:"ishigaki"}, wiki:"Ishigaki,_Okinawa"},
  { city:"Fukuoka", country:"Japan", lat:33.5904, lon:130.4017, iata:"FUK", region:"East Asia", budget:"thrifty", whyNow:"Food & bays", socials:{ig:"fukuoka"}, wiki:"Fukuoka"},
  { city:"Jeju", country:"South Korea", lat:33.4996, lon:126.5312, iata:"CJU", region:"East Asia", budget:"thrifty", whyNow:"Volcanic island", socials:{ig:"jeju"}, wiki:"Jeju_Island"},
  { city:"Hong Kong", country:"China (HK)", lat:22.3193, lon:114.1694, iata:"HKG", region:"East Asia", budget:"expensive", whyNow:"Harbor skyline", socials:{ig:"hongkong"}, wiki:"Hong_Kong"},
  { city:"Hualien (Taiwan)", country:"Taiwan", lat:23.9911, lon:121.6114, iata:"HUN", region:"East Asia", budget:"thrifty", whyNow:"Taroko coast", socials:{ig:"taiwan"}, wiki:"Hualien"},

  // ===== CENTRAL ASIA =====
  { city:"Almaty", country:"Kazakhstan", lat:43.2220, lon:76.8512, iata:"ALA", region:"Central Asia", budget:"cheap", whyNow:"Mountains & cafes", socials:{ig:"almaty"}, wiki:"Almaty"},

  // ===== OCEANIA =====
  { city:"Sydney", country:"Australia", lat:-33.8688, lon:151.2093, iata:"SYD", region:"Oceania", budget:"expensive", whyNow:"City/beach mix", socials:{ig:"sydney"}, wiki:"Sydney"},
  { city:"Melbourne", country:"Australia", lat:-37.8136, lon:144.9631, iata:"MEL", region:"Oceania", budget:"thrifty", whyNow:"Culture & coffee", socials:{ig:"melbourne"}, wiki:"Melbourne"},
  { city:"Brisbane", country:"Australia", lat:-27.4698, lon:153.0251, iata:"BNE", region:"Oceania", budget:"thrifty", whyNow:"Beachy city", socials:{ig:"brisbane"}, wiki:"Brisbane"},
  { city:"Gold Coast", country:"Australia", lat:-28.0167, lon:153.4000, iata:"OOL", region:"Oceania", budget:"thrifty", whyNow:"Surf & parks", socials:{ig:"goldcoast"}, wiki:"Gold_Coast,_Queensland"},
  { city:"Sunshine Coast", country:"Australia", lat:-26.6500, lon:153.0667, iata:"MCY", region:"Oceania", budget:"thrifty", whyNow:"Relaxed beaches", socials:{ig:"sunshinecoast"}, wiki:"Sunshine_Coast,_Queensland"},
  { city:"Cairns", country:"Australia", lat:-16.9186, lon:145.7781, iata:"CNS", region:"Oceania", budget:"thrifty", whyNow:"Reef gateway", socials:{ig:"cairns"}, wiki:"Cairns"},
  { city:"Whitsunday Coast", country:"Australia", lat:-20.2763, lon:148.7557, iata:"PPP", region:"Oceania", budget:"boujie", whyNow:"Islands & Whitehaven", socials:{ig:"whitsundays"}, wiki:"Whitsunday_Islands"},
  { city:"Darwin", country:"Australia", lat:-12.4634, lon:130.8456, iata:"DRW", region:"Oceania", budget:"thrifty", whyNow:"Tropical Top End", socials:{ig:"darwin"}, wiki:"Darwin,_Northern_Territory"},
  { city:"Perth", country:"Australia", lat:-31.9523, lon:115.8613, iata:"PER", region:"Oceania", budget:"thrifty", whyNow:"Sunniest capital", socials:{ig:"perth"}, wiki:"Perth"},
  { city:"Adelaide", country:"Australia", lat:-34.9285, lon:138.6007, iata:"ADL", region:"Oceania", budget:"thrifty", whyNow:"Wine & coast", socials:{ig:"adelaide"}, wiki:"Adelaide"},
  { city:"Hobart", country:"Australia", lat:-42.8821, lon:147.3272, iata:"HBA", region:"Oceania", budget:"thrifty", whyNow:"Cooler escape", socials:{ig:"hobart"}, wiki:"Hobart"},
  { city:"Auckland", country:"New Zealand", lat:-36.8509, lon:174.7645, iata:"AKL", region:"Oceania", budget:"thrifty", whyNow:"Harbour city", socials:{ig:"auckland"}, wiki:"Auckland"},
  { city:"Queenstown", country:"New Zealand", lat:-45.0312, lon:168.6626, iata:"ZQN", region:"Oceania", budget:"boujie", whyNow:"Adventure hub", socials:{ig:"queenstown"}, wiki:"Queenstown,_New_Zealand"},
  { city:"Nadi", country:"Fiji", lat:-17.7765, lon:177.4350, iata:"NAN", region:"Oceania", budget:"boujie", whyNow:"Resorts & reefs", socials:{ig:"fiji"}, wiki:"Nadi"},
  { city:"Nouméa", country:"New Caledonia", lat:-22.2740, lon:166.4416, iata:"NOU", region:"Oceania", budget:"boujie", whyNow:"French Pacific", socials:{ig:"noumea"}, wiki:"Nouméa"},
  { city:"Port Vila", country:"Vanuatu", lat:-17.7333, lon:168.3273, iata:"VLI", region:"Oceania", budget:"thrifty", whyNow:"Lagoons & blue holes", socials:{ig:"vanuatu"}, wiki:"Port_Vila"},
  { city:"Apia", country:"Samoa", lat:-13.8333, lon:-171.7667, iata:"APW", region:"Oceania", budget:"thrifty", whyNow:"Polynesian paradise", socials:{ig:"samoa"}, wiki:"Apia"}
];
